import type { Product } from '@/models/Product';

export const initialProducts: Product[] = [
    {
      _id: 'prod_001',
      name: 'Monochrome Echo Tee',
      price: 34.99,
      category: 'Oversized',
      images: ['https://placehold.co/400x500.png', 'https://placehold.co/400x500.png'],
      sizes: ['S', 'M', 'L', 'XL'],
      description: 'A comfortable oversized tee with a subtle, echoing monochrome graphic. Perfect for a relaxed, modern look.',
      details: ['100% premium cotton', 'Oversized fit', 'Dropped shoulders'],
      fabricAndCare: 'Machine wash cold, tumble dry low. Do not bleach. Iron on low heat.',
      isTrending: true,
      isNew: false,
    },
    {
      _id: 'prod_002',
      name: 'Urban Canvas Hoodie',
      price: 69.99,
      category: 'Hoodie',
      images: ['https://placehold.co/400x500.png', 'https://placehold.co/400x500.png'],
      sizes: ['M', 'L', 'XL'],
      description: 'A heavyweight hoodie that serves as your urban canvas. Features a clean design and a comfortable fleece interior.',
      details: ['80% cotton, 20% polyester fleece', 'Kangaroo pocket', 'Ribbed cuffs and hem'],
      fabricAndCare: 'Machine wash warm. Tumble dry medium. Do not iron decoration.',
      isTrending: true,
      isNew: false,
    },
    {
      _id: 'prod_003',
      name: 'Shadow Stripe Long Sleeve',
      price: 42.00,
      category: 'Full Sleeves',
      images: ['https://placehold.co/400x500.png'],
      sizes: ['S', 'M', 'L'],
      description: 'A stylish long sleeve shirt with subtle shadow stripes. Versatile for both casual and smart-casual occasions.',
      details: ['95% cotton, 5% elastane', 'Slim fit', 'Crew neck'],
      fabricAndCare: 'Wash with like colors. Do not use fabric softeners.',
      isTrending: false,
      isNew: true,
    },
    {
      _id: 'prod_004',
      name: 'Minimalist Signature Tee',
      price: 29.99,
      category: 'Half Sleeves',
      images: ['https://placehold.co/400x500.png'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      description: 'The essential tee, perfected. Made from ultra-soft pima cotton with a minimalist embroidered signature.',
      details: ['100% Pima cotton', 'Classic fit', 'Embroidered logo'],
      fabricAndCare: 'Machine wash cold. Lay flat to dry for best results.',
      isTrending: true,
      isNew: true,
    },
    {
      _id: 'prod_005',
      name: 'Fable-Knit Sweatshirt',
      price: 55.50,
      category: 'Sweatshirt',
      images: ['https://placehold.co/400x500.png'],
      sizes: ['L', 'XL'],
      description: 'Our signature Fable-Knit fabric in a classic sweatshirt silhouette. Unmatched softness and durability.',
      details: ['Proprietary Fable-Knit fabric', 'Relaxed fit', 'V-notch detail at neck'],
      fabricAndCare: 'Gentle cycle recommended. Tumble dry low.',
      isTrending: false,
      isNew: true,
    },
    {
      _id: 'prod_006',
      name: 'Noir Essential Tee',
      price: 28.00,
      category: 'Half Sleeves',
      images: ['https://placehold.co/400x500.png'],
      sizes: ['S', 'M', 'L'],
      description: 'A timeless black tee that forms the foundation of any wardrobe. Crafted for comfort and style.',
      details: ['100% combed cotton', 'Standard fit', 'Tagless neck label'],
      fabricAndCare: 'Machine wash, gentle cycle. Avoid high heat.',
      isTrending: false,
      isNew: false,
    },
    {
      _id: 'prod_007',
      name: 'Asymmetric Flow Tee',
      price: 36.00,
      category: 'Oversized',
      images: ['https://placehold.co/400x500.png'],
      sizes: ['M', 'L'],
      description: 'Break the mold with this asymmetric tee. The unique cut and flowy fabric create a dynamic silhouette.',
      details: ['Modal-cotton blend', 'Asymmetric hem', 'Loose, draping fit'],
      fabricAndCare: 'Hand wash or use a delicates bag. Hang to dry.',
      isTrending: true,
      isNew: true,
    },
    {
      _id: 'prod_008',
      name: 'Static Graphic Hoodie',
      price: 75.00,
      category: 'Hoodie',
      images: ['https://placehold.co/400x500.png'],
      sizes: ['S', 'M', 'L', 'XL'],
      description: 'A bold statement piece. This hoodie features a high-impact "static" graphic on a premium black base.',
      details: ['Heavyweight French Terry cotton', 'Screen-printed graphic', 'Double-lined hood'],
      fabricAndCare: 'Wash inside out. Do not iron directly on the graphic.',
      isTrending: false,
      isNew: true,
    },
  ];
